import {StyleSheet} from 'react-native';

export default Styles = StyleSheet.create({
  content: {
    color: '#000',
    flex: 1,
  },
  title: {
    color: '#426897',
    fontSize: 26,
    margin: 5,
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#426897',
  },
  label: {
    color: '#426897',
    margin: 5,
  },
  input: {
    color: '#426897',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 5,
    margin: 5,
    padding: 15,
  },
  inline: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 3,
  },
  btn: {
    color: '#fff',
    backgroundColor: '#426897',
    padding: 15,
    margin: 5,
    borderRadius: 15,
  },
  btnText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 16,
  },
  homeBtn: {
    flexDirection: 'row',
    backgroundColor: '#426897',
    padding: 3,
    borderRadius: 5,
    margin: 2,
    alignItems: 'center',
  },
  grid: {
    marginTop: 15,
    flexDirection: 'row',
    //flexWrap: 'wrap',
  },
  btnImg: {
    resizeMode: 'contain',
    margin: 5,
    padding: 5,
    width: 40,
    height: 40,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 15,
    margin: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 1,
  },
  cardText: {
    color: '#000',
  },
  cardContentText: {
    color: '#000',
    fontSize: 20,
    margin: 3,
  },
  cardTitle: {
    fontSize: 23,
    color: '#000',
  },
  headerBtn: {
    color: '#fff',
    backgroundColor: '#426897',
    padding: 5,
    margin: 5,
    borderRadius: 15,
  },
  headerBtnImg: {
    resizeMode: 'contain',
    margin: 5,
    padding: 5,
    width: 20,
    height: 20,
  },
  logo: {
    resizeMode: 'contain',
    width: 200,
    height: 200,
    alignSelf: 'center',
  },
  paragraph: {
    color: '#000',
    fontSize: 20,
    textAlign: 'justify',
    margin: 4,
    whiteSpace: 'pre-line',
  },
  floatingBtn: {
    position: 'absolute',
    zIndex: 12,
    backgroundColor: '#426897',
    bottom: 12,
    margin: 15,
    right: 0,
    borderRadius: 50,
    padding: 3,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 1,
  },
  floatingBtnImg: {
    resizeMode: 'contain',
    margin: 5,
    padding: 5,
    width: 50,
    height: 50,
    borderRadius: 3,
    backgroundColor: '#426897',
  },
});
